### ISSUE TITLE
Build error causes slc start to fail

### ISSUE THREAD

**Issue by danielblignaut** [strongloop/loopback#1730]
Hi, Every time I install strongloop globally, I get the following npm install failure. I read up about a previous issue referencing a problem with npm 3 (https://github.com/strongloop/strongloop/issues/248). My current setup is using the latest node stable (4.1.2) with npm (2.14.4). If it's relevant, I'm using nvm to handle my node version. Here's the npm install dump:
```
vagrant@precise64:/var/www/node/strongloop/journalSystem$ npm install -g strongloop
 
> utf-8-validate@1.2.1 install /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp: /home/vagrant/.node-gyp/4.1.2/common.gypi not found (cwd: /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/ws/node_modules/utf-8-validate) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
 stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.1.2/bin/node" "/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
 
> bufferutil@1.2.1 install /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp: /home/vagrant/.node-gyp/4.1.2/common.gypi not found (cwd: /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/ws/node_modules/bufferutil) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.1.2/bin/node" "/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1
 
> heapdump@0.3.7 install /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump
> node-gyp rebuild

gyp: /home/vagrant/.node-gyp/4.1.2/common.gypi not found (cwd: /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.1.2/bin/node" "/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing heapdump@0.3.7
 
> strong-agent@1.6.4 install /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-agent
> node-gyp rebuild || exit 0

gyp: /home/vagrant/.node-gyp/4.1.2/common.gypi not found (cwd: /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-agent) while reading includes of binding.gyp while trying to load binding.gyp
configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.1.2/bin/node" "/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-agent
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
 
> modern-syslog@1.1.1 install /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/modern-syslog
> node-gyp rebuild

gyp: /home/vagrant/.node-gyp/4.1.2/common.gypi not found (cwd: /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/modern-syslog) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.1.2/bin/node" "/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/modern-syslog
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing modern-syslog@1.1.1
 
> strong-agent@2.0.2 install /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-agent
> node-gyp rebuild || exit 0

gyp: /home/vagrant/.node-gyp/4.1.2/common.gypi not found (cwd: /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-agent) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.1.2/bin/node" "/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-agent
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
 
> strong-debugger@1.0.0 install /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-debugger
> node-gyp rebuild

gyp: /home/vagrant/.node-gyp/4.1.2/common.gypi not found (cwd: /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-debugger) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.1.2/bin/node" "/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-debugger
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing strong-debugger@1.0.0
 
> spawn-sync@1.0.13 postinstall /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

npm WARN deprecated jsonstream@1.0.3: use JSONStream instead
 
> ws@0.4.32 install /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
> sqlite3@3.1.0 install /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node" is installed via remote
npm WARN deprecated showdown@0.3.1: IMPORTANT hotfix
npm WARN deprecated react-tools@0.10.0: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
 
> heapdump@0.3.7 install /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-supervisor/node_modules/heapdump
> node-gyp rebuild

gyp: /home/vagrant/.node-gyp/4.1.2/common.gypi not found (cwd: /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-supervisor/node_modules/heapdump) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.1.2/bin/node" "/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-supervisor/node_modules/heapdump
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
 
> strong-fork-syslog@1.2.3 install /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-supervisor/node_modules/strong-fork-syslog
> node-gyp rebuild

gyp: /home/vagrant/.node-gyp/4.1.2/common.gypi not found (cwd: /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-supervisor/node_modules/strong-fork-syslog) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.1.2/bin/node" "/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-supervisor/node_modules/strong-fork-syslog
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing heapdump@0.3.7
npm WARN optional dep failed, continuing strong-fork-syslog@1.2.3
 
> bufferutil@1.1.0 install /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp: /home/vagrant/.node-gyp/4.1.2/common.gypi not found (cwd: /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/bufferutil) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.1.2/bin/node" "/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.1.2
 v2.0.2! node-gyp -v\
gyp ERR! not ok 
 
> utf-8-validate@1.1.0 install /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp: /home/vagrant/.node-gyp/4.1.2/common.gypi not found (cwd: /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/utf-8-validate) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v4.1.2/bin/node" "/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
|
> strong-mesh-client@1.6.3 install /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-mesh-client
> node proxy/build-client.js

browser bundle successfully generated
/home/vagrant/.nvm/versions/node/v4.1.2/bin/slc -> /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/bin/slc.js
/home/vagrant/.nvm/versions/node/v4.1.2/bin/lb-ng -> /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng
/home/vagrant/.nvm/versions/node/v4.1.2/bin/lb-ng-doc -> /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng-doc
strongloop@5.0.1 /home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop
├── sl-blip@1.0.0
├── once@1.3.2
├── core-util-is@1.0.1
├── vhost@3.0.2
├── wrappy@1.0.1
├── minimatch@2.0.10
├── ansi-regex@1.1.1
├── inherits@2.0.1
├── inflight@1.0.4
├── ms@0.7.0
├── async@0.9.2
├── mime-db@1.8.0
├── qs@2.4.2
├── mime-types@2.1.7 (mime-db@1.19.0)
├── debug@2.2.0 (ms@0.7.1)
├── read@1.0.7 (mute-stream@0.0.5)
├── brace-expansion@1.1.1 (concat-map@0.0.1, balanced-match@0.2.0)
├── response-time@2.3.1 (on-headers@1.0.1, depd@1.0.1)
├── readable-stream@1.1.13 (string_decoder@0.10.31, isarray@0.0.1)
├── cookie-parser@1.4.0 (cookie-signature@1.0.6, cookie@0.2.2)
├── bluebird@2.10.2
├── nopt@3.0.4 (abbrev@1.0.7)
├── morgan@1.6.1 (on-headers@1.0.1, basic-auth@1.0.3, depd@1.0.1, on-finished@2.3.0)
├── connect-timeout@1.7.0 (on-headers@1.0.1, ms@0.7.1, on-finished@2.3.0, http-errors@1.3.1)
├── errorhandler@1.4.2 (escape-html@1.0.2, accepts@1.2.13)
├── compression@1.6.0 (bytes@2.1.0, on-headers@1.0.1, vary@1.1.0, compressible@2.0.6, accepts@1.3.0)
├── acorn@0.9.0
├── which@1.2.0 (is-absolute@0.1.7)
├── JSONStream@1.0.6 (through@2.3.8, jsonparse@1.2.0)
├── cookie-session@1.2.0 (on-headers@1.0.1, cookies@0.5.0)
├── method-override@2.3.5 (vary@1.0.1, methods@1.1.1, parseurl@1.3.0)
├── serve-favicon@2.3.0 (etag@1.7.0, fresh@0.3.0, ms@0.7.1, parseurl@1.3.0)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── strong-start@1.3.2 (posix-getopt@1.2.0, mkdirp@0.5.1, osenv@0.1.3)
├── express-session@1.11.3 (cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, on-headers@1.0.1, parseurl@1.3.0, depd@1.0.1, crc@3.3.0, uid-safe@2.0.0)
├── csurf@1.8.3 (cookie@0.1.3, cookie-signature@1.0.6, http-errors@1.3.1, csrf@3.0.0)
├── ws@0.8.0 (options@0.0.6, ultron@1.0.2)
├── serve-index@1.7.2 (escape-html@1.0.2, parseurl@1.3.0, batch@0.5.2, http-errors@1.3.1, accepts@1.2.13)
├── serve-static@1.10.0 (escape-html@1.0.2, parseurl@1.3.0, send@0.13.0)
├── loopback-boot@2.14.0 (commondir@0.0.1, toposort@0.2.12, semver@4.3.6)
├── strong-agent@1.6.4 (semver@2.2.1, strong-license@1.2.1)
├── loopback-datasource-juggler@2.41.0 (inflection@1.7.2, depd@1.1.0, async@1.0.0, node-uuid@1.4.3, qs@3.1.0, loopback-connector@2.3.0, traverse@0.6.6)
├── strong-build@2.0.6 (posix-getopt@1.2.0, shelljs@0.4.0, vasync@1.6.3, json-file-plus@3.0.1)
├── strong-supervisor@3.2.2 (async@1.4.2, posix-getopt@1.2.0, strong-url-defaults@1.2.1, dotenv@1.2.0, strong-cluster-control@2.2.1, strongloop-license@1.5.1, strong-trace@1.3.3, strong-control-channel@2.1.1, strong-statsd@2.0.4, strong-agent@2.0.2, strong-npm-ls@1.0.7, strong-log-transformer@1.0.3)
├── nodefly-register@0.3.3
├── strong-mesh-models@8.0.0 (sprintf@0.1.5, user-home@1.1.1, posix-getopt@1.2.0, strong-url-defaults@1.2.1, text-table@0.2.0, concat-stream@1.5.0, strong-tunnel@1.1.4, strong-npm-ls@1.0.7, request@2.65.0, http-auth@2.2.8)
├── strong-pm@5.0.1 (strong-spawn-npm@1.0.0, userhome@1.0.0, posix-getopt@1.2.0, extsprintf@1.3.0, strong-url-defaults@1.2.1, strong-runner@5.0.1, rimraf@2.4.3, mkdirp@0.5.1, concat-stream@1.5.0, bl@0.9.4, express@4.13.3, strong-control-channel@2.1.1, tar@1.0.3, strong-service-install@2.0.1, strong-fork-cicada@1.1.2, dockerode@2.2.3, strong-tunnel@1.1.4, strong-docker-build@1.1.0, strong-npm-ls@1.0.7, http-auth@2.2.8)
├── loopback-workspace@3.18.2 (stable@0.1.5, strong-wait-till-listening@1.0.1, debug@1.0.4, ncp@2.0.0, fs-extra@0.22.1, glob@4.0.6, loopback-component-explorer@2.1.1)
├── lodash@3.10.1
├── strong-registry@1.1.5 (ini@1.3.4, osenv@0.0.3, semver@2.3.2, commander@2.9.0, rimraf@2.4.3, bluebird@1.2.4, inquirer@0.4.1)
├── strong-deploy@3.1.2 (posix-getopt@1.2.0, strong-url-defaults@1.2.1, shelljs@0.3.0, concat-stream@1.5.0, strong-tunnel@1.1.4, strong-mesh-models@7.1.1)
├── generator-loopback@1.12.0 (async@1.4.2, inflection@1.7.2, chalk@1.1.1, yosay@1.0.5, loopback-swagger@2.1.2, js-yaml@3.4.3, request@2.65.0, yeoman-generator@0.20.3)
├── loopback@2.22.2 (uid2@0.0.3, stable@0.1.5, nodemailer-stub-transport@0.1.5, inflection@1.7.2, canonical-json@0.0.4, depd@1.1.0, loopback-phase@1.2.0, loopback-connector-remote@1.0.3, bcryptjs@2.3.0, body-parser@1.14.1, express@4.13.3, ejs@2.3.4, underscore.string@3.2.2, continuation-local-storage@3.1.4, nodemailer@1.8.0, strong-remoting@2.21.0)
├── node-inspector@0.7.4 (debug@0.8.1, opener@1.3.0, which@1.0.9, async@0.8.0, yargs@1.2.6, strong-data-uri@0.1.1, rc@0.3.5, glob@3.2.11, ws@0.4.32, express@4.0.0)
├── loopback-explorer@1.8.0 (lodash@2.4.2, cors@2.7.1, debug@1.0.4, express@3.21.2, swagger-ui@2.0.24)
├── minkelite@1.2.5 (xtend@4.0.0, util@0.10.3, ago@1.0.0, stats-lite@1.0.3, md5@2.0.0, body-parser@1.9.3, express@4.9.8, sqlite3@3.1.0)
├── loopback-sdk-angular-cli@1.1.4 (semver@2.3.2, loopback-sdk-angular@1.5.0, express@3.21.2, docular@0.6.6)
└── strong-arc@1.8.2 (parse-ms@1.0.0, path@0.11.14, opener@1.4.1, strong-trace-waterfall@1.1.3, minimist@1.2.0, sha1@1.1.1, split@0.3.3, http-proxy@1.11.2, node-underscorify@0.0.14, cxviz-color@1.0.1, fs-extra@0.16.5, page@1.6.3, strong-trace-waterfalltransform@1.0.1, request@2.65.0, express@4.13.3, cxviz-format@1.0.1, cxviz-flame@1.0.1, cxviz-eventloop@1.0.1, cxviz-rawtree@1.0.1, cxviz-timeseries@1.0.2, cxviz-pie@1.0.1, strong-trace-waterfalldata@1.0.1, strong-pm@3.2.1, express-jsxtransform@1.1.0, strong-mesh-client@1.6.3)
vagrant@precise64:/var/www/node/strongloop/journalSystem$ slc
usage: slc <-h|--help|-v|--version>
usage: slc <command> [--help] [...]
```

Strongloop succeeds to install and I can run slc:loopback as well as node . and my project will run, however when I run slc start, I get the following error. Trying to install the strong-debugger package also fails to build. Below is the dump from an slc start command.

```
Error: Cannot find module 'strong-debugger/package.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-supervisor/lib/runctl.js:4:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
Unexpected exit with 1 from Runner: commit journalSystem/local-directory
Start Runner: commit journalSystem/local-directory
module.js:338
    throw err;
    ^

````

**Comment by superkhau** [comment]
@rmg ^

**Comment by rmg** [comment]
Duplicate of strongloop/strong-pm#286 and will be resolved by strongloop/strong-supervisor#166.

**Comment by rmg** [comment]
@danielblignaut strong-supervisor@3.3.0 has been released and should fix this. Please re-run `npm install -g strongloop` to get the update and let us know if it works for you.

**Comment by danielblignaut** [comment]
I've re-run ```npm install -g strongloop``` and I'm no longer getting any make or gyp failures on install but on running ```slc start```, I am still getting this:

```
Error: Cannot find module 'strong-debugger/package.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/.nvm/versions/node/v4.1.2/lib/node_modules/strongloop/node_modules/strong-supervisor/lib/runctl.js:4:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
Unexpected exit with 1 from Runner: commit journalSystem/local-directory
Start Runner: commit journalSystem/local-directory
module.js:338
    throw err;
    ^


```

**Comment by superkhau** [comment]
For future reference, please post `slc` issues at https://github.com/strongloop/strongloop.

**Comment by rmg** [comment]
@danielblignaut you will need to stop and start strong-pm. It seems to be retaining a reference to the old version - the line referenced in that error doesn't even exist in the updated version.

**Comment by surfjedi** [comment]
+1

**Comment by rmg** [comment]
I'm closing this for now. @danielblignaut please re-open if it is still a problem for you.
