### ISSUE TITLE
Cannot migrate models not attached to this datasource: Application 

### ISSUE THREAD

**Issue by margagn** [strongloop/loopback#2073]
I just followed the following tutorial (https://docs.strongloop.com/display/public/LB/Connect+your+API+to+a+data+source) and I was able to see the CoffeeShop table in my SQL Server Express 2014. However, as soon as I change the dataSource for the built-in models (User, Application, etc.) I get the following error: "Cannot migrate models not attached to this datasource: Application".

Any idea what is going on?

Thank you!

### create-sample-model.js
```
module.exports = function(app) {
    
  app.dataSources.sqlserver.automigrate(['User', 'Application', 'Role', 'ACL', 'RoleMapping', 'AccessToken'], function(err) { 
    if (err) throw err;
  });
  
  app.dataSources.sqlserver.automigrate('CoffeeShop', function(err) {
    if (err) throw err;
 
    app.models.CoffeeShop.create([
      {name: 'Bel Cafe', city: 'Vancouver'},
      {name: 'Three Bees Coffee House', city: 'San Mateo'},
      {name: 'Caffe Artigiano', city: 'Vancouver'},
    ], function(err, coffeeShops) {
      if (err) throw err;
 
      console.log('Models created: \n', coffeeShops);
    });
  });
};
```

### model-config.json
```
{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ],
    "mixins": [
      "loopback/common/mixins",
      "loopback/server/mixins",
      "../common/mixins",
      "./mixins"
    ]
  },
  "User": {
    "dataSource": "sqlserver"
  },
  "AccessToken": {
    "dataSource": "sqlserver",
    "public": false
  },
  "ACL": {
    "dataSource": "sqlserver",
    "public": false
  },
  "RoleMapping": {
    "dataSource": "sqlserver",
    "public": false
  },
  "Role": {
    "dataSource": "sqlserver",
    "public": false
  },
  "CoffeeShop": {
    "dataSource": "sqlserver"
  }
}
 ```

### datasources.json
```
{
  "sqlserver": {
    "host": "MyMachine",
    "database": "demo",
    "username": "User",
    "password": "password",
    "name": "sqlserver",
    "connector": "mssql",
    "debug": true,
    "options": {
      "encrypt": false,
      "instance": "SQLEXPRESS"
    }
  }
}
```

**Comment by gunjpan** [comment]
@margagn: You're getting that error because in your `model-config.json` file, `Application` model is missing and thus not bound to a datasource.
> The file /server/model-config.json configures LoopBack models, for example it binds models to data sources and specifies whether a model is exposed over REST.  The models referenced in this file must be either a built-in models or custom models defined by a JSON file in the common/models/ folder. 

_([Read more here](https://docs.strongloop.com/display/public/LB/model-config.json))_  

Adding following to your `model-config.json` file will resolve the issue.
```json
  "Application": {
    "dataSource": "sqlserver"
  },
```
Interesting reading on: [How to use built-in models](https://docs.strongloop.com/display/public/LB/Using+built-in+models) & [Creating database schema from Models](https://docs.strongloop.com/display/public/LB/Creating+a+database+schema+from+models).

Hope that helps, enjoy! Closing for now, please feel free to re-open if you above solution does not work for you/have more questions. Thank you.

**Comment by mprogers** [comment]
I ran into this problem about a year after this was closed, and this suggestion resolved it -- so doesn't this need to be fixed in the tutorial?

**Comment by superkhau** [comment]
@mprogers Would you like to contribute a fix to the tutorial? I can help you get it landed if you're interested.

**Comment by perceptron007** [comment]
@superkhau The documentation seems to be missing so many issues. I think i can understand your situation you might be facing a lot of issues. Assign me. I can fix this problem.

**Comment by superkhau** [comment]
@perceptron007 Would you like to contribute some documentation via pull requests? Ping me directly in there and let's get your proposed document fixes landed.

**Comment by mpereira-dev** [comment]
This is still an issue. The proposed solution did nothing for me. FWIW I'm using Mysql.

**Comment by VisionMkhabela** [comment]
Any solution to this issue?? 

rror: Cannot migrate models not attached to this datasource: User AccessToken ACL RoleMapping Role

**Comment by MarkHC** [comment]
Same problem. It says it cannot migrate even though my model is attached to the same datasource as all others.

**Comment by adambant** [comment]
> Any solution to this issue??
> 
> rror: Cannot migrate models not attached to this datasource: User AccessToken ACL RoleMapping Role

Did you try the fix mentioned by gunjpan commented on Feb 17, 2016?

**Comment by pizza-hut** [comment]
Hey, in 2020, I have the same problem. I followed the tute step by step and I use the strongloop sql.

Error: Cannot migrate models not attached to this datasource: CoffeeShop

/server/datasources.js
  "localDs": {
    "host": "127.0.0.1",
    "port": 3306,
    "url": "",
    "database": "demo",
    "password": "...",
    "name": "localDs",
    "user": "...",
    "connector": "mysql"
  }
}

server/model-config.js
`  "Coffeeshop": {
    "dataSource": "localDs",
    "public": true
  }`
