### ISSUE TITLE
Multi-User Problem Using ACL and Extended Models Issues

### ISSUE THREAD

**Issue by sebastianfelipe** [strongloop/loopback#2516]
Hi friends,

There is a big problem. I've implemented a solution, but I think there have to be a real update from the loopback team. Here the case:
- There are 2 users, userA and userB. Both extend from the User model
- userA has a lot of rows with users already registered from 1 to n, and userB from 1 to m
- You loggin with userA, and you can do for example GET userAs/idGivenWhenLoggedIn and you will have an answer, but...
- You can also do GET userBs/idGivenWhenLoggedIn, without have logged in with userB. This issue is when both share the same userId, case it doesn't discriminate with the model used to log in, just the userId -> poblem.

This is very insecure, that can drive many developers that haven't found a solution yet, to make mistakes and maybe without realising.

The same thing is when it used the $owner and the $authenticate, etc. to create ACL rules. I implemented a solution to those cases, adding a custom "roleResolver", extending an accessTokenCustom model  from the accessToken model, and adding the attribute "model" when some model logged in (the ones that extend from the User model). But those things, doesn't solve the initial problem, planted above.

One thing we can do is:
- Implement my solution + reset the ACLs (can that be possible?) + implement everything from scratch, without using the $authenticated and $owner roles
- Loopback developers, implement those changes, because it drives us to many errors that are hard to handle in small and, overall, big platforms.

The solution I comment above, is that (I wrote those lines in a general way):
- RoleResolver:

```
Role.registerResolver("customRole", function(role, context, cb) {
          function reject(err) {
              if(err) {
                  return cb(err);
              }
              cb(null, false);
          }
          if(!context.accessToken.userId) {
              console.log("anonymous user is logged in");
              return reject(); // do not allow anonymous users
          }
          if (context.accessToken.model == "Model") {

              if (context.modelName == "Model")
              {
                if (context.modelId == context.accessToken.userId)
                {
                  console.log("Model is logged in with id");
                  return cb(null, true);
                }
              }
              else
              {
                  console.log("Model is logged in");
                  return cb(null, true);
              }
          }
          reject();
  });
```
- ACL (is an example of the use)

```
{
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "customRole",
      "permission": "ALLOW"
    }
```
- AccessTokenCustom (model based in AccessToken)

```
{
  "name": "AccessTokenCustom",
  "base": "AccessToken",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  }
```
- Replace accessTokens relations in models extended from the User model:
  
  ```
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "AccessTokenCustom",
      "foreignKey": "userId"
    }
  }
  ```
- Finally, fill the model attribute when a user log in:

```
    userExtendedFromUserModel.prototype.createAccessToken = function(ttl, options, cb) {
        if (cb === undefined && typeof options === "function") {
          // createAccessToken(ttl, cb)
          cb = options;
          options = undefined;
        }

        cb = cb || utils.createPromiseCallback();

        if (typeof ttl === "object" && !options) {
          // createAccessToken(options, cb)
          options = ttl;
          ttl = options.ttl;
        }
        options = options || {};
        var userModel = this.constructor;
        ttl = Math.min(ttl || userModel.settings.ttl, userModel.settings.maxTTL);
        this.accessTokens.create({
          ttl: ttl,
          model: userModel.modelName
        }, cb);
        return cb.promise;
    };
```

This solution that I created with the help of some answers, most of them from this issues, is not enough. We really need something powerful, something from the root. In this moment I'm working in a project and I need to find a elegant way to do these things.

That solution doesn't solve the problem I presented above. Maybe it could be solved using a extended User model without inherit its ACL rules and the solution commented. Supposing this case, there is some way to extend a model from a base model without inherit its ACL rules? If the answer is yes, I really appreciate know "how" (for now), otherwise what can I do to solve the main problem?

For now, I suggest (from your side, the loopback team):
- Add the "Model Name" as a column in the AccessToken, that would be very useful to implement custom role resolvers and also to not modifying the prototype method (is not a good idea do that)
- Enable the model option to reset the ACL rules when you extend from a model.

With both, is possible to implement better solutions using loopback. I believe there are better ones rather than mine, but ok, it's a good point to start with, and are not very complex to implement in a release (soon please, I really need it).

I'd really appreciate your help.

Thanks,
Sebastián.

**Comment by richardpringle** [comment]
@bajtos @loay, please review.

**Comment by richardpringle** [comment]
@sebastianfelipe 

With the current `AccessToken`/`login` implementation, I think it's safe to say that LoopBack does not support an application with multiple User models without unique IDs between them.

Perhaps we can make that a future consideration.

cc/ @raymondfeng

**Comment by richardpringle** [comment]
@crandmck 

It might be a good idea to specifically document the limitations of extending the built-in User model, what do you think?

**Comment by raymondfeng** [comment]
The current version of LoopBack has to pick one official User/AccessToken as there is no concept of user partition. With multiple user registries, a discriminator is needed, for example, realm or organization so that user federation/delegation can happen.
 
For future releases, we are evaluating it as part of multi-tenancy support. For example, we can adopt the github model, which consists of organization/team/user.

**Comment by crandmck** [comment]
> It might be a good idea to specifically document the limitations of extending the built-in User model, what do you think?

Yes, we should add this.  How would you word it?  Perhaps something like: 

> LoopBack does not support an application with multiple User models.  You can extend the built-in User model <link>, but by default you cannot have more than one User model in a single app. 

Is that sound right?

**Comment by richardpringle** [comment]
>...more than one User model in a single app.

I would say something like "... more than one model of type-User" or maybe "base-User". 

I'm trying to mitigate any potential confusion.

**Comment by crandmck** [comment]
Added a note to:

- http://loopback.io/doc/en/lb2/Managing-users.html
- http://loopback.io/doc/en/lb2/Using-built-in-models.html#user-model

**Comment by ebarault** [comment]
@crandmck, @richardpringle  could you reopen this issue?

I was facing a similar "organization/teams/members" advanced access control situation and after deeply looking into the whole loopback access control logic i've successfully built a relation set with custom AccessToken, Role, RoleMapping and Users models (extending built-in models) allowing to use any number of User-based models while relying on a a single instance of AccessToken, Role and RoleMapping extended models.

The solution requires to enable polymorphism on existing hasMany, hasManyThrough and BelongsTo relations binding the different models all together, as well as very little patches in the AccessContext class and the Role model isInRole method to handle the polymorphic discriminator when querying the role mappings to resolve effective ACLs.

Would you consider @strongloop-team looking into a related sample app and related PR, or do you plan a totally different scenario to cover this use case?

**Comment by richardpringle** [comment]
Hey @ebarault, I'm not currently working on the framework but @superkhau might be a good person to mention in a PR. I'm sure it would be a great contribution!

Otherwise, I would open a new issue as a feature request with the new issue template.

Cheers and good luck!

**Comment by crandmck** [comment]
I don't believe this is a doc issue _per se_.  From @ebarault's comment above, it sounds like we could either create a new sample app, add this to an existing example app (e.g. [loopback-example-relations](https://github.com/strongloop/loopback-example-relations) ), and perhaps enhance LoopBack relation model feature (but I'm unclear if this is feasible).  

Anyway, I'll remove the doc label for now and change to discussion.

**Comment by ebarault** [comment]
I pushed a PR enabling loopback to play with multiple User based models. Could you please have a look ?

**Comment by svanbaelen** [comment]
Is the functionality mentioned by @ebarault available?

**Comment by ebarault** [comment]
Hi @svanbaelen : yes!
Take a look at http://loopback.io/doc/en/lb3/Authentication-authorization-and-permissions.html
and search for the "Access control with multiple user models" section

**Comment by ebarault** [comment]
Closing as available

**Comment by hendratommy** [comment]
Hi,

I think http://loopback.io/doc/en/lb3/Authentication-authorization-and-permissions.html have an bug with permissions.

I created 2 user models extended from User (BackOfficeUser and Customer), and 1 access token extended from AccessToken (CustomAccessToken) and set it up like the docs.

I create an ACL for each BackOfficeUser and Customer like the following:
```
"acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY",
      "property": "*"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "*"
    },
    {
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "create"
    }
  ]
```
My expected result is only the owner (it self) can access /api/{MODELS}/{ID}

Here is my test case and result:

- Create 2 BackOfficeUser and 2 Customer
- Login BackOfficeUser with id 1
- Access to /api/BackOfficeUsers/1 => SUCCESS (Expected)
- Access to /api/BackOfficeUsers/1 => DENIED (Expected)
- Access to /api/Customers/1 => SUCCESS (Not Expected)
- Access to /api/Customers/2 => DENIED (Expected)
 
 
- Login Customer with id 2:
- Access to /api/Customers/1 => DENIED (Expected)
- Access to /api/Customers/2 => SUCCESS (Expected)
- Access to /api/BackOfficeUsers/1 => DENIED (Expected)
- Access to /api/BackOfficeUsers/2 => SUCCESS (Not Expected)

So i think the ACL cannot differentiate between BackOfficeUser with id 1, and Customer with id 1.

Any suggestion or workarround? I'm using loopback 3.8.0.

**Comment by sebastianfelipe** [comment]
Hi. I unerstood that this feature was implemented in Loopback 3. But to make it real, you have to specify a polymorphic relation, between user models and the access token model. Did you do that? :)

**Comment by hendratommy** [comment]
Hi,

I did. I did exactly like the doc said. Below is my models:
```
{
  "name": "CustomAccessToken",
  "base": "AccessToken",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {
    "user": {
      "type": "belongsTo",
      "idName": "id",
      "polymorphic": {
        "idType": "string",
        "foreignKey": "userId",
        "discriminator": "principalType"
      }
    }
  },
  "acls": [],
  "methods": {}
}
```
```
{
  "name": "Customer",
  "plural": "Customers",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "CustomAccessToken",
      "polymorphic": {
        "foreignKey": "userId",
        "discriminator": "principalType"
      },
      "options": {
        "disableInclude": true
      }
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY",
      "property": "*"
    },
    {
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "create"
    }
  ],
  "methods": {}
}
```

```
{
  "name": "BackOfficeUser",
  "plural": "BackOfficeUsers",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "CustomAccessToken",
      "polymorphic": {
        "foreignKey": "userId",
        "discriminator": "principalType"
      },
      "options": {
        "disableInclude": true
      }
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY",
      "property": "*"
    },
    {
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "create"
    }
  ],
  "methods": {}
}
```
You can download my test project at:
https://drive.google.com/open?id=0B1PeypjU-qrGY0k5V0lzLUtrQk0

**Comment by ebarault** [comment]
hi, yes, actually the built-in dynamic role $owner does not currently support multi-user models in case 2 users have the same id, which can happen with SQL dbs, but never happens with MongoDB for example.

I have a pull-request in progress to address this.

What db are you using?

**Comment by sebastianfelipe** [comment]
So... Why this thread is closed? Specifically, that was the problem before and what I see is that is not solved yet. Well, you always can create a role-resolver with a custom owner, comparing de moldeName and modelId from the url with the model name and id from the fetched access token. If you need it, you can do it as well. Cheers.

**Comment by ebarault** [comment]
well, it is very specific to the **$owner** dynamic role which is currently very limited. the solution provided with multi-user support allows you to create a custom role resolver.

i'd suggest to open a new issue rather than reopening this one.

**Comment by hendratommy** [comment]
> What db are you using?
I'm using mysql db in my actual project, but the test project i've uploaded earlier use in-memory db.

> this last comment makes me think you have something badly configured. it should not work.
In my test project, it just an simple project. I just create new empty serve with 3 models. So i don't think i've add weird things. I will double check this.

**Comment by ebarault** [comment]
i'm sorry, but it's quite hard to investigate like this. Could you fork and share on your github account the loopback sandbox?
https://github.com/strongloop/loopback-sandbox

**Comment by hendratommy** [comment]
Hi,

Sure. Here is my fork from loopback-sandbox:
https://github.com/hendratommy/my-loopback-sandbox-defaultacl

**Comment by sebastianfelipe** [comment]
Hey man, sorry for the late. To prevent that bug use what I proposed above. Is a patch over the problem. It doesn't rely on the polymorphic one. I have used it in some projects and make the correspondents tests and everything works perfectly. Cheers.

**Comment by sebastianfelipe** [comment]
This thread is unsolved yet. Recently I implemented the polymorphic relation and the $owner permission is not enough. Is necessary to explicitly implement a verification of the modelName or the principalType as it is implemented in the polymorphic relation. That means if your entering to /Admin/2, then the accessToken needs to be userId: 1 AND principalType: Admin, not other. In my case, I could use the resource (data from an specific endpoint), using an accessToken from an Admin2. Thanks.

**Comment by sebastianfelipe** [comment]
Adding to this possible solution, in the model definition "common/models/role.js", line 224 Role.isOwner contains the necessary method to validate if a User is an owner or not. In that case, there is an operation that validate if the user is a User class or a SubClass of a User class. There is the problem.

First, in line 250 ->  if (isUserClass(modelClass)), where is the verification if the model class is a user model or a subclass of a user model. Nested to that, in line 253 -> if (principalType === Principal.USER || principalType === userModelName), we finally find that the OR logic operation is not enough to discriminate whether the model is DIRECTLY related to the model, and not a submodel or something similar. For example, a User class inherits its properties to a CustomUser1 and a CustomUser2, using the lines 250 and 253, a CustomUser2 can use a CustomUser1 resource with an $owner permission, because is a sub class from a User model, and the line 250 is passing it, and then the OR operation do the same. For me that is the mistake we need to solve, that needs to be related EXACTLY with the modelName used in the endpoint, not a subclass or submodel.

If I'm right, there is the solution of it and I think no extra patch from us as developers is needed. I hope to be right and help to solve it.

Thanks,
Sebastián.

**Comment by Lahrachtdi** [comment]
the built-in dynamic role $owner still not working with multiple-user model even when we do exactly what's in the docs, also there is some mistakes in the doc when they give solutions for static roles assignments for multiple-user models, but still don't work, I started redefining dynamic roles myself and I think this gonna work, here is my custom dynamic role $owner definition maybe it can help you.

```
module.exports = function definingDynamicRoles(app) {
  const Role = app.models.Role;

  Role.registerResolver('$owner', (role, context, next) => {
    const userId = context.accessToken.userId;
    const userPrincipalType = context.accessToken.$principalType;
    const tagetModelPrincipalType = context.modelName;
    const targetInstanceId = context.modelId;

    // Q: Is the user logged in? (there will be an accessToken with an ID if so)
    if (!userId) {
      return process.nextTick(() => next(null, false));
    }

    if (userPrincipalType !== tagetModelPrincipalType) {
      return process.nextTick(() => next(null, false));
    }

    if (parseInt(targetInstanceId, 10) !== userId) {
      return process.nextTick(() => next(null, false));
    }
    return process.nextTick(() => next(null, true));
  });

};

```

**Comment by sebastianfelipe** [comment]
Yes, I have custom roles too, but is not the idea if that role exists by default.

**Comment by ghassenlassoued** [comment]
Hi , since this discussion was  6 months ago, I need to ask again if there are any solutions ?
