### ISSUE TITLE
'findById' returns 200

### ISSUE THREAD

**Issue by joni-toivonen** [strongloop/loopback#3694]
api/TestModels/{id]

returns a 200 response if the element was found.

If the element was not found, it still returns 200.

The proper behavior when the element is not found should be to return 404

Edit:
Created an empty loopback application:
```
lb
name of application: loopback-test
loopback version: 3.x (current)
empty-server
cd loopback-test
```

common/models/test-model.js:
```
'use strict';

module.exports = function(Testmodel) {

};
```

common/models/test-model.json:
```
{
  "name": "TestModel",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

package.json:
```
{
  "name": "loopback-test",
  "version": "1.0.0",
  "main": "server/server.js",
  "engines": {
    "node": ">=4"
  },
  "scripts": {
    "lint": "eslint .",
    "start": "node .",
    "posttest": "npm run lint && nsp check"
  },
  "dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^1.3.0",
    "loopback": "^3.0.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^5.0.0",
    "loopback-connector-redis": "^0.1.0",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^2.0.0"
  },
  "devDependencies": {
    "eslint": "^3.17.1",
    "eslint-config-loopback": "^8.0.0",
    "nsp": "^2.1.0"
  },
  "repository": {
    "type": "",
    "url": ""
  },
  "license": "UNLICENSED",
  "description": "loopback-test"
}
```

server/datasources.json:
```
{
  "redis1": {
    "name": "redis1",
    "host": "127.0.0.1",
    "port": 6379,
    "url": "",
    "password": "",
    "database": 0,
    "connector": "redis"
  }
}
```

server/model-config.json:
```
{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ],
    "mixins": [
      "loopback/common/mixins",
      "loopback/server/mixins",
      "../common/mixins",
      "./mixins"
    ]
  },
  "TestModel": {
    "dataSource": "redis1",
    "public": true
  }
}
```

Connector: Redis (using the loopback-connector-redis as seen in package.json, Redis is running on docker, can be found here: https://hub.docker.com/_/redis/)
```
docker pull redis
docker run --name loopback-test-redis -d -p 6379:6379 redis
```

Running the loopback-test:
```
npm install
node .
```

node version:
win32 x64 8.9.1

loopback version (ran the command on git bash):
+-- loopback@3.16.2
+-- loopback-boot@2.27.0
+-- loopback-component-explorer@5.2.0
+-- loopback-connector-redis@0.1.0

**Comment by dhmlau** [comment]
Could you please provide more information? 
- any sample app
- which connector
- node version and loopback versions:
   ```
   Copy+paste the output of these two commands:
     node -e 'console.log(process.platform, process.arch, process.versions.node)'
     npm ls --prod --depth 0 | grep loopback
   ```

**Comment by joni-toivonen** [comment]
@dhmlau I added more information

**Comment by viguirilo** [comment]
I have tested in my new project and I couldn't reproduce this behaviour you are reporting.

Here is my request:

`http://localhost:3000/api/Tests/1`

Here is the response:

```
{
  "error": {
    "statusCode": 404,
    "name": "Error",
    "message": "Unknown \"Test\" id \"1\".",
    "status": 404,
    "code": "MODEL_NOT_FOUND",
    "stack": "foo bar"
  }
}
```

And here is my `package.json`

```
{
  "name": "teste",
  "version": "1.0.0",
  "main": "server/server.js",
  "engines": {
    "node": ">=4"
  },
  "scripts": {
    "lint": "eslint .",
    "start": "node .",
    "posttest": "npm run lint && nsp check"
  },
  "dependencies": {
    "compression": "^1.7.1",
    "cors": "^2.8.4",
    "helmet": "^3.9.0",
    "loopback": "^3.17.0",
    "loopback-boot": "^2.27.0",
    "loopback-component-explorer": "^5.2.0",
    "loopback-connector-mongodb": "^3.3.0",
    "serve-favicon": "^2.4.5",
    "sqlite3": "^3.1.13",
    "strong-error-handler": "^2.3.0",
    "strongloop": "^6.0.3"
  },
  "devDependencies": {
    "eslint": "^4.12.1",
    "eslint-config-loopback": "^8.0.0",
    "nsp": "^3.1.0"
  },
  "repository": {
    "type": "",
    "url": ""
  },
  "license": "UNLICENSED",
  "description": "teste"
}
```

Probably this bug has been fixed in the most recent versions.


```
$ node --version
v6.11.4
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

**Comment by joni-toivonen** [comment]
I just tried to replicate it and the problem still persists.
The problem might have something to do with how loopback handles redis.
