### ISSUE TITLE
MongoDB Error Message in Strong Loop

### ISSUE THREAD

**Issue by Dawensky** [strongloop/loopback#3764]
# Description/Steps to reproduce
I am using "Strongloop" to initiate connection with mongodb. After reading through the log error (slc ctl log- dumb MY-SERVICE-NAME) couple of times, the constant complain is **"Error: Cannot create "data source:" Cannot initialize connector "loopback-connector-mongodb": Username containing an unescaped at-sign".** Below is my configuration in the datasource.json provided by strongloop

"mongo": {
"name": "mongo",
"connector": "loopback-connector-mongodb",
"url": "mongodb://user:psd@db1.exam...:27017,db2.example.com:27017/db-name?replicaSet=replica_set_name&poolSize=25&autoReconnect=true&reconnectTries=100&reconnectInterval=3000&connectTimeoutMS=30000&socketTimeoutMS=30000&maxPoolSize=25&w=majority&wtimeoutMS=3000"
},

I am not sure what I am doing wrong. And how should I set the URL for the replica set in regards to the "mongo db1.example.com" for mongo shell. Also, I am using mongoDB 3.4.10

Thanks guru. I count on your advice as I wasted enough time on this

**Comment by dhmlau** [comment]
@Dawensky , We just released loopback-connector-mongodb 3.4.0, which pulls in mongodb driver 3.x. You should be able to use encoded user/pass now without extra options to be set.

cc @raymondfeng

**Comment by dhmlau** [comment]
Another way is to encode the `@` with `%40`. 
Closing this issue as we believe your issue has been resolved.  Thanks.

**Comment by NgaNguyenDuy** [comment]
Hi, I still can't connect via url string?
So, what is exactly of URL string format.
